server:
  port: 8001
mybatis:
  type-aliases-package: com.alex.coaching.model        # 所有Entity别名类所在包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
debug: true
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java

  mvc:
    static-path-pattern: /static/**

  resources:
    static-locations: classpath:/static/

  thymeleaf:
    cache: false
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    encoding: UTF-8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver        # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/coaching?serverTimezone=GMT%2B8  # 数据库名称
    username: root
    password: root
    min-idle: 5                                # 数据库连接池的最小维持连接数
    initial-size: 5                            # 初始化连接数
    max-total: 5                               # 最大连接数
    max-wait-millis: 150                       # 等待连接获取的最大超时时间







