package com.alex.coaching.service;

import com.alex.coaching.model.MaterialIn;

import java.util.List;
import java.util.Map;

public interface MaterialInService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_out
     *
     * @mbggenerated Thu Nov 28 15:29:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_out
     *
     * @mbggenerated Thu Nov 28 15:29:15 CST 2019
     */
    int insert(MaterialIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_out
     *
     * @mbggenerated Thu Nov 28 15:29:15 CST 2019
     */
    int insertSelective(MaterialIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_out
     *
     * @mbggenerated Thu Nov 28 15:29:15 CST 2019
     */
    MaterialIn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_out
     *
     * @mbggenerated Thu Nov 28 15:29:15 CST 2019
     */
    int updateByPrimaryKeySelective(MaterialIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_out
     *
     * @mbggenerated Thu Nov 28 15:29:15 CST 2019
     */
    int updateByPrimaryKey(MaterialIn record);

    List<Map<String,Object>> getLnList(int materialId);

    int  getAllMaterialInCount(MaterialIn record);

     List<MaterialIn> getAllMaterialIn(MaterialIn materialIn, String outDateMin, String outDateMax,
                                        int page, int limit);

}