package com.alex.coaching.model;

import java.util.Date;

public class MaterialIn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_in.id
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_in.lot_number
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    private String lotNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_in.material_id
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    private Integer materialId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_in.name
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_in.num
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_in.specifications
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    private String specifications;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_in.total
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    private Double total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_in.stock
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    private Double stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_in.in_storage_time
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    private Date inStorageTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_in.id
     *
     * @return the value of material_in.id
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_in.id
     *
     * @param id the value for material_in.id
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_in.lot_number
     *
     * @return the value of material_in.lot_number
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    public String getLotNumber() {
        return lotNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_in.lot_number
     *
     * @param lotNumber the value for material_in.lot_number
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    public void setLotNumber(String lotNumber) {
        this.lotNumber = lotNumber == null ? null : lotNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_in.material_id
     *
     * @return the value of material_in.material_id
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    public Integer getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_in.material_id
     *
     * @param materialId the value for material_in.material_id
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    public void setMaterialId(Integer materialId) {
        this.materialId = materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_in.name
     *
     * @return the value of material_in.name
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_in.name
     *
     * @param name the value for material_in.name
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_in.num
     *
     * @return the value of material_in.num
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_in.num
     *
     * @param num the value for material_in.num
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_in.specifications
     *
     * @return the value of material_in.specifications
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    public String getSpecifications() {
        return specifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_in.specifications
     *
     * @param specifications the value for material_in.specifications
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    public void setSpecifications(String specifications) {
        this.specifications = specifications == null ? null : specifications.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_in.total
     *
     * @return the value of material_in.total
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_in.total
     *
     * @param total the value for material_in.total
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_in.stock
     *
     * @return the value of material_in.stock
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    public Double getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_in.stock
     *
     * @param stock the value for material_in.stock
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    public void setStock(Double stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_in.in_storage_time
     *
     * @return the value of material_in.in_storage_time
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    public Date getInStorageTime() {
        return inStorageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_in.in_storage_time
     *
     * @param inStorageTime the value for material_in.in_storage_time
     *
     * @mbggenerated Fri Nov 29 15:13:33 CST 2019
     */
    public void setInStorageTime(Date inStorageTime) {
        this.inStorageTime = inStorageTime;
    }
}